alter table public.events add column if not exists location text;
alter table public.events add column if not exists city text;
alter table public.events add column if not exists district text;
alter table public.events add column if not exists risk_level text default 'low';
alter table public.events add column if not exists risk_tags jsonb default '[]'::jsonb;
alter table public.events add column if not exists recommended_action text;
alter table public.events add column if not exists weather_snapshot jsonb;
alter table public.events add column if not exists weather_checked_at timestamptz;
alter table public.events add column if not exists weather_alert_status text default 'none';
alter table public.events add column if not exists external_source text;
alter table public.events add column if not exists external_event_id text;
alter table public.events add column if not exists last_synced_at timestamptz;

alter table public.sync_logs add column if not exists source text default 'backend';
alter table public.sync_logs add column if not exists payload jsonb default '{}'::jsonb;
alter table public.sync_logs add column if not exists finished_at timestamptz;

create table if not exists public.ai_suggestion_cache (
  cache_key text primary key,
  prompt_type text,
  subject text,
  context_hash text,
  response jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.event_weather_alerts (
  id bigint generated by default as identity primary key,
  event_id text,
  title text,
  message text not null,
  severity text default 'medium',
  change_summary jsonb default '{}'::jsonb,
  suggested_location text,
  status text default 'unread',
  created_at timestamptz default now()
);

create table if not exists public.emergency_kit_scans (
  id bigint generated by default as identity primary key,
  user_id text,
  kit_id text,
  detected_items jsonb default '[]'::jsonb,
  missing_items jsonb default '[]'::jsonb,
  extra_items jsonb default '[]'::jsonb,
  confidence double precision default 0,
  notes text,
  created_at timestamptz default now()
);
