create table if not exists public.incident_reports (
  id bigint generated by default as identity primary key,
  source text default 'threads',
  source_id text,
  source_url text,
  incident_type text default 'unknown',
  title text,
  summary text,
  location_text text,
  locations jsonb default '[]'::jsonb,
  confidence double precision default 0,
  evidence_count integer default 0,
  status text default 'candidate',
  raw jsonb default '{}'::jsonb,
  last_seen_at timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.incident_reports add column if not exists source text default 'threads';
alter table public.incident_reports add column if not exists source_id text;
alter table public.incident_reports add column if not exists source_url text;
alter table public.incident_reports add column if not exists incident_type text default 'unknown';
alter table public.incident_reports add column if not exists title text;
alter table public.incident_reports add column if not exists summary text;
alter table public.incident_reports add column if not exists location_text text;
alter table public.incident_reports add column if not exists locations jsonb default '[]'::jsonb;
alter table public.incident_reports add column if not exists confidence double precision default 0;
alter table public.incident_reports add column if not exists evidence_count integer default 0;
alter table public.incident_reports add column if not exists status text default 'candidate';
alter table public.incident_reports add column if not exists raw jsonb default '{}'::jsonb;
alter table public.incident_reports add column if not exists last_seen_at timestamptz default now();
alter table public.incident_reports add column if not exists created_at timestamptz default now();

create unique index if not exists incident_reports_source_url_idx
  on public.incident_reports(source_url)
  where source_url is not null and source_url <> '';

create index if not exists incident_reports_last_seen_idx on public.incident_reports(last_seen_at desc);
create index if not exists incident_reports_type_idx on public.incident_reports(incident_type);

create table if not exists public.incident_evidence (
  id bigint generated by default as identity primary key,
  incident_id bigint references public.incident_reports(id) on delete cascade,
  source text,
  source_id text,
  source_url text,
  text text,
  extracted_locations jsonb default '[]'::jsonb,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists incident_evidence_incident_id_idx on public.incident_evidence(incident_id);

create table if not exists public.incident_notifications (
  id bigint generated by default as identity primary key,
  incident_id bigint references public.incident_reports(id) on delete cascade,
  user_id text,
  channel text default 'in_app',
  status text default 'queued',
  sent_at timestamptz,
  error_message text,
  created_at timestamptz default now()
);

create index if not exists incident_notifications_status_idx on public.incident_notifications(status);
