-- Deduplicate event weather alerts generated by repeated cron runs.

alter table public.event_weather_alerts
  add column if not exists notification_key text;

create unique index if not exists event_weather_alerts_notification_key_idx
  on public.event_weather_alerts(notification_key)
  where notification_key is not null;
