-- Weather history, heat injury fields, user preferences, and push device tokens.

alter table public.weather_cache add column if not exists wbgt integer default 0;
alter table public.weather_cache add column if not exists heat_injury_warning text;

create table if not exists public.weather_observations (
  id bigint generated by default as identity primary key,
  city_name text not null,
  city text,
  district text,
  observed_at timestamptz not null,
  current jsonb default '{}'::jsonb,
  risk_level text default 'low',
  risk_tags jsonb default '[]'::jsonb,
  data_sources jsonb default '{}'::jsonb,
  source_errors jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  unique(city_name, observed_at)
);

create index if not exists weather_observations_city_observed_idx
  on public.weather_observations(city_name, observed_at desc);

create table if not exists public.user_preferences (
  user_id text primary key,
  default_city text,
  default_district text,
  commute_mode text,
  risk_preferences jsonb default '{}'::jsonb,
  quiet_hours jsonb default '{}'::jsonb,
  favorite_locations jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.push_device_tokens (
  id bigint generated by default as identity primary key,
  user_id text not null,
  platform text not null,
  provider text not null,
  device_token text not null,
  token_hash text unique not null,
  app_version text,
  device_name text,
  is_active boolean default true,
  last_seen_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists push_device_tokens_user_active_idx
  on public.push_device_tokens(user_id, is_active, updated_at desc);

notify pgrst, 'reload schema';
